'use strict';

module.exports = [
  'Errornotifications',
  'Extremeforecast',
  'ExtremesWWC',
  'Forestfireindex',
  'Geosatellite',
  'Gribfiles',
  'Icemap',
  'Locationforecast',
  'LocationforecastLTS',
  'Metgm',
  'Mountaineasterobservations',
  'Oceanforecast',
  'Polarsatellite',
  'Probabilityforecast',
  'Radar',
  'Seaapproachforecast',
  'Seasonforecast',
  'Subjectiveforecast',
  'Sunrise',
  'Temperatureverification',
  'Textforecast',
  'Textlocation',
  'Tidalwater',
  'Trondheimsleia',
  'Turbulence',
  'UVforecast',
  'Weatherformetnosite',
  'Weathericon',
  'Windforecast'
];
