'use strict';

module.exports = [
  'Errornotifications',
  'Extremeforecast',
  'ExtremesWWC',
  'Forestfireindex',
  'Geosatellite',
  'Gribfiles',
  'Icemap',
  'Lightning',
  'Locationforecast',
  'LocationforecastLTS',
  'MetAlerts',
  'Metgm',
  'Mountaineasterobservations',
  'Nowcast',
  'Oceanforecast',
  'Polarsatellite',
  'Probabilityforecast',
  'Radar',
  'Radarlightning', 
  'Sigmets',
  'Spotwind',
  'Subjectiveforecast',
  'Sunrise',
  'Tafmetar',
  'Temperatureverification',
  'Textforecast',
  'Textlocation',
  'Tidalwater',
  'Turbulence',
  'UVforecast',
  'Upperwindweather',
  'VerticalProfile',
  'Weathericon'
];
